### ISSUE TITLE
Tiny jobs

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1288]
We often have small tasks which can be fixed very easy. E.g. Typos, doumentaiton updates, etc. It's not always profitable for project to accept these tasks and pay to reporter 15min, performer 30min, CR 15min and QA 8min. This is why people don't whant to submit small issues. I think we can invent another flow for tiny tasks:
ARC can say `@0crat tiny` or add `tiny` label to issue,
author will receive 5min for reporting
this job will be added to WBS with boos=1x (15min) and assigned to ARC who can fix it directly in master branch without review.
So project will pay 20min instead of 68min.

@yegor256 what do you think?

**Comment by llorllale** [comment]
@g4s8 unless we open the "funding floodgates", this will do the opposite of helping to move projects forward in "meaningful" ways.

For example, I would never ever want to pay for something like this to be honest: yegor256/cactoos#912. A project's funds are a very valuable resource and to have them used up like this (even with tiny boosts) is, to me, unacceptable.

So until we are suddenly drowning with funds, I still appreciate the tolerance currently afforded to the `ARC` by the policy in [§29](http://www.zerocracy.com/policy.html#29).

I think the way it works now is better: we encourage users to open bugs, some will be accepted, some won't be, and as they keep investigating they will spot bugs/opportunities of substance instead of cosmetics and, in the end, the project may even gain a valuable `DEV` or `REV`.

**Comment by g4s8** [comment]
@llorllale this issue was fixed with ARC release bonuses.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1288` is not assigned, can't get performer
