### ISSUE TITLE
Speed Bonus should be considered if impediments are applied

### ISSUE THREAD

**Issue by liligga** [zerocracy/farm#1418]
I believe [Speed Bonus](http://www.zerocracy.com/policy.html#36) is neglected when job in 'impediment mode'. I think this should be rectified and time of job being in 'wait' mode should be subtracted from the total age so that `DEV` could be able to achieve 'Speed Bonus'. I think the current implementation of impediments should be considered as well as 
 [this proposal](https://github.com/zerocracy/farm/issues/1138#issuecomment-402062734) ( when programmers would be able to suspend jobs). 
PS: As far as I understand this feature can be abused.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@liligga[/z](https://www.0crat.com/u/liligga) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@liligga speed bonus was created to encourage developers to deliver results faster, because it's profitable for the project. If the performer uses impediments and not deliver the result fast, there are no benefits for the project, regardless how fast was performer and how much time he spent on a job. So I don't see a resons to pay extra money to developers for fast working if they can't deliver results fast.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1418` is not assigned, can't get performer
