### ISSUE TITLE
Github events should be processed in order of time not arrival

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#1497]
It seems that sometimes 0crat receives events from github in the wrong order, for example in zold-io/java-api#52 I had to close and reopen the PR (see #1496 as to why).

So what happened is that 0crat first saw the issue being opened, it put it in scope, and then a few minutes later, it saw the issue being closed and removed it from scope.

In the end I had to close it and simply open a new PR.

I think that there should be some kind of queuing mechanism in 0crat for external events that put them in order or time and not arrival.
One problem is how long should we wait before taking an event into account (since maybe one that happened sooner could be arriving after).
I suppose this is a common problem for github bots, maybe this was solved somewhere else?

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by victornoel** [comment]
@g4s8 ping

**Comment by g4s8** [comment]
@victornoel I don't think it's relevant, because:
 1. 0crat has a queue of events which is designed to be processed simultaneously: when 0crat received first event it starts to process it, then it can receive second event and start process it too, but second event may be processed faster than first and it's a normal situation. Even more, it's designed to work on multiple instances, so second event can be process on different machine, and we don't know about first GitHub event.
 2. 0crat processes the queue based on priority: direct user actions goes first (profile and project management via Telegram or Slack channels), then GitHub webhook events, then other routine operations, so if 0crat receives GitHub event and it can't be processed right now (if all workers are busy) and then it receives user event from Slack channel, then it processes Slack event first when any worker becomes free despite receiving time - this event just have higher priority.

**Comment by victornoel** [comment]
@g4s8 ok, so the solution I propose is not good, but the problem itself is real. Should I rewrite the description or open a new issue?

**Comment by g4s8** [comment]
@victornoel I think each problem is unique here, even if many of them looks similar but requires different work to solve it, so please submit different bugs for each inconsistent behavior, like this: https://github.com/zerocracy/farm/issues/2005

**Comment by victornoel** [comment]
@g4s8 I've created #2029, thanks

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1497` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
