### ISSUE TITLE
Duplicate claim id of pings

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1659]
There are many exceptions in Sentry about duplicate claim ids for `Ping` claims:
```
java.lang.IllegalArgumentException: Claim #2390829319 (Ping) already exists for C3FFK3YAY
    at com.zerocracy.claims.Footprint.open(Footprint.java:111)
    at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:68)
    at com.zerocracy.claims.proc.FootprintProc.exec(FootprintProc.java:32)
    at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:66)
    at com.zerocracy.claims.proc.SentryProc.exec(SentryProc.java:29)
    at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:63)
    at com.zerocracy.claims.proc.ExpiryProc.exec(ExpiryProc.java:32)
    at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:157)
    at com.zerocracy.claims.proc.MessageMonitorProc.exec(MessageMonitorProc.java:52)
    at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
```
It seems that claim id is not really unique, we need to investigate and fix this.
https://sentry.io/zerocracy/farm/issues/656907018/

**Comment by 0crat** [comment]
The job [#1659](https://github.com/zerocracy/farm/issues/1659) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2402131797); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 21days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@g4s8 I have a hypothesis about what's causing this:

The CID is actually formed by adding together two things:

* The current time in the following format: (`DDDHHMM000`)
(where `DDD` is the nth day of the year (e.g. Sept. 21 is 264), `HH` is hours, `MM` is minutes)
---> September 21, 01:35 would be `2640135000`
* An incrementing `AtomicLong`

The first number increases every minute by 1000 due to the 000 placeholder), while each call to `new ClaimOut()` increases the second number by 1.

So, if we exceed 1000 claims we can possibly come up with numbers representing dates into the future. Now here's where my maths skills are a bit challenged - we expect both numbers to increase, so I can't come up with an example where the combination of date and counter increasing potentially leads to a collision of numbers.

Looking at the Sentry report for this also shows that the numbers can potentially go "backwards" in time, or maybe I'm reading it wrong: https://sentry.io/zerocracy/farm/issues/656907018/events/?cursor=1537501304000%3A0%3A0

I can increase the placeholder zeros of the first number to say, six figures (millions), but I can't think of a test to cause the collisions that we're seeing. What do you think?

**Comment by g4s8** [comment]
@carlosmiranda it seems to be possible after release (when claim counter is reset to zero).
E.g. it increases from `1` to `1001` in one minute in `September 21, 01:35`, so `cid`'s range is `2640135001` -> `2640136001`, after new release this counter becomes `0` again, so after one minute `cid` can be `2640136001`.

Maybe it's better to use `UUID.randomUUID()` for claim ids, what do yu think? It should be safe enough: https://stackoverflow.com/a/1155027

**Comment by carlosmiranda** [comment]
@g4s8 please see #1723

**Comment by carlosmiranda** [comment]
@0crat wait for merge of #1723

**Comment by carlosmiranda** [comment]
@g4s8 also raised issue in Datum, see https://github.com/zerocracy/datum/issues/388

**Comment by 0crat** [comment]
> @0crat wait for merge of #1723 ([here](https://github.com/zerocracy/farm/issues/1659#issuecomment-423892451))

@carlosmiranda The impediment for [#1659](https://github.com/zerocracy/farm/issues/1659) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by g4s8** [comment]
@carlosmiranda PR #1723 was merged, thanks

**Comment by g4s8** [comment]
@rultor release, tag=`0.37.1`

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1659](https://github.com/zerocracy/farm/issues/1659) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
