### ISSUE TITLE
As a mentor I don't receive any tuition fee from students

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/farm#1661]
On the Team page I see that my students have some points (e.g. "peter-kehl" has +30 and "timeracers" has +15). But I didn't receive any tuition fee from these points - there was no notification in telegram of 0crat and nothing in debt list.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@ypshenychka peter-kehl submitted two bugs: https://github.com/yegor256/wring/issues/65 and https://github.com/zerocracy/farm/issues/1576 but didn't receive money for them, because he is not a project member, (he received only points).
timeracers did receive only points for https://github.com/yegor256/0pdd/issues/228 job also (it seems that he hadn't configured the rate before was assigned to this job).
In both cases users didn't receive any cash, this is why you also didn't receive tution fee.

**Comment by ypshenychka** [comment]
@g4s8 Ok, got it. Thanks for explanation.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1661` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
