### ISSUE TITLE
Consider dropping Groovy

### ISSUE THREAD

**Issue by victornoel** [zerocracy/farm#1719]
This is a difficult issue, but I think it should be said: Groovy is hell to work with.

Some small changes to the codebase (see #1305) took way too long to tackle because of Groovy: it's not typed so it is really hard to find where things are broken when changing the type of class.
I'm not even talking about changing a string somewhere, but an actual object type.
This should be simplest act during programming, and it became something really complex.

And in the end, I'm not even sure I succeeded in fixing all the Groovy errors because it seems they are raised only if the code is executed: let's hope the test base of zerocracy is strong enough.

Furthermore, isn't groovy a dead language? If we need something lighter than Java in terms of code, there are better alternative I think.

I propose that we bit by bit move all the Groovy code to either Java, or for example Kotlin if we want less boilerplate.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by victornoel** [comment]
@g4s8 for the record, while fixing a simple task such as #1282, it took me way more than 30mn just because groovy is such a pain to work with. Between bad IDE support and back-and-forth because of typing errors impossible to understand (I had to copy paste my code in Java to understand the problem with it), it doubled the time it took me.

**Comment by g4s8** [comment]
@victornoel groovy is used here to write procedural script files without classes which can be executed in runtime and has java bindings. It is not used as a language with cool syntax or light version of java. To avoid type issues you should always use type names instead of `def` keyworkd: `Awards awards = new Awards(farm, user)`, not `def awards = new Awards(farm, user)`. You can try to use "Intellij IDEA" to work with groovy code, it seems that it has better support of this language.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1719` is not assigned, can't get performer
