### ISSUE TITLE
Notify PMO on each Coinbase payment

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1747]
We notify PMO on each PayPal payment at the moment. Let's do the same for Coinbase payments.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1747](https://github.com/zerocracy/farm/issues/1747) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1747](https://github.com/zerocracy/farm/issues/1747), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.39.2`

**Comment by g4s8** [comment]
@yegor256 fixed

**Comment by 0crat** [comment]
Job [#1747](https://github.com/zerocracy/farm/issues/1747) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add
