### ISSUE TITLE
Ledger.java:41-43: We should allow negative balance only...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/farm#1790]
The puzzle `1658-f3d9a105` from #1658 has to be resolved: 

https://github.com/zerocracy/farm/blob/62e971ddadff30e50e48550d695703f8d58d4834/src/main/java/com/zerocracy/pm/cost/Ledger.java#L41-L43

The puzzle was created by Kirill on 21-Nov-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1790](https://github.com/zerocracy/farm/issues/1790) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1790](https://github.com/zerocracy/farm/issues/1790), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
The puzzle `1658-f3d9a105` has disappeared from the source code, that's why I closed this issue.

**Comment by g4s8** [comment]
@rultor release, tag=`0.38.3`

**Comment by g4s8** [comment]
@rultor release, tag=`0.38.3`
