### ISSUE TITLE
0crat unassigned issue due to cancelled pull request

### ISSUE THREAD

**Issue by dgroup** [zerocracy/farm#1797]
The history: https://github.com/llorllale/cactoos-matchers/issues/32.
The pull request for this task was raised in the top of the wrong branch, thus, it was closed and a new PR was raised.

As we can see now, the 0crat unsigned the issue.
What is the reason for such behavior, as I couldn't find it in the www.zerocracy.com/policy.html.

**Comment by g4s8** [comment]
@dgroup as I can see this issue is assigned to you, see https://github.com/llorllale/cactoos-matchers/issues/32#issuecomment-441356843

Actually there is no relation between issue and pull request for 0crat, you can open as many pull request for one issue as needed (or zero PRs).

Also you can check job status with command: `status` in Github.

**Comment by dgroup** [comment]
@g4s8 , thanks a lot for the clarification.
Not a bug.

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1797` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
