### ISSUE TITLE
0crat failed to pay for estimated job

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1811]
0crat skipped cash payment for estimated job

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1811](https://github.com/zerocracy/farm/issues/1811), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1811` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@rultor release, tag=`0.38.6`

**Comment by paulodamaso** [comment]
@g4s8 Please take a look at this, I have some jobs that were not paid due this.

**Comment by g4s8** [comment]
@paulodamaso should be fixed now

**Comment by 0crat** [comment]
Job [#1811](https://github.com/zerocracy/farm/issues/1811) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1811](https://github.com/zerocracy/farm/issues/1811) is now out of scope
