### ISSUE TITLE
Remove paypal payment option

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1860]
Same as in https://github.com/zerocracy/farm/issues/1843
remove paypal payment option.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1860](https://github.com/zerocracy/farm/issues/1860), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1860` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by Vatavuk** [comment]
@g4s8 Does this mean that developers are now going to be paid only with zold, there will be no other option available?

**Comment by g4s8** [comment]
@Vatavuk yes, but before that, limitation for zold exchange will be removed for 0crat users, so you will be able to exchange any amount of zold

**Comment by Vatavuk** [comment]
@g4s8 What's the reasoning behind this decision? I will be forced to do double conversion to get to the money paying fees for both conversion. Zold -> Bitcoin (8%) and Bitcoin -> Paypal (there is some fee because Im not US citizen).

**Comment by g4s8** [comment]
@Vatavuk we have some issues with Paypal. I suppose you will be able to sell ZLD directly to your currency without BTC conversion and most probably ZLD->BTC fee will be removed for Zerocracy users.
@yegor256 can you clarify this question please?

**Comment by amihaiemil** [comment]
@g4s8 @yegor256 I, for one, want to be paid in real money, not crypto. So unless you add some other cash payment method (or just leave PayPal as it is), I'm afraid I'll be out --and I think I am not the knly one with this opinion.

**Comment by emilianodellacasa** [comment]
@g4s8 Just to have another opinion on this matter, I am not against removing paypal payments as it is slow and (I can imagine) quite expensive. 

If we are forced to choose another payment option involving conversion fees I guess we could just raise our rates accordingly, no big deal.

However.

The good thing of PayPal is its reliability - you can be 100% (well, let's say 99.999%) sure that payments don't get lost, and when we talk about money people wants to be super sure he/she is not going to lose monet because of  a glitch. 

Which super-very reliable alternatives will we have, after removing PayPal?

**Comment by krzyk** [comment]
@g4s8 I'm in the same boat as @amihaiemil, "only crypto" is no option for  me. It is good to have it as an alternative, but with main payment method being something with old-school money (not necessarily PayPal).

**Comment by yegor256** [comment]
@g4s8 how about we simply pay +10% to the USD/ZLD current rate? This will cover all commissions, I believe.

**Comment by yegor256** [comment]
@Vatavuk there are a number of reasons:

1. Multiple payment options make Zerocrat software too complicated and turn it into a micro-bank, full of potential risks

2. When something goes wrong, Zerocrat has to hold the money and technically act as a bank -- this is not our business at all.

3. PayPal will very soon start blocking our operations for multiple reasons. We can't even predict what may happen. We can't rely on them and we don't want to stop our business one day because they simply will require "some extra document, bla-bla-bla."

Put this all together. Zold solves all these problems.

**Comment by g4s8** [comment]
> how about we simply pay +10% to the USD/ZLD current rate? This will cover all commissions, I believe.

@yegor256 I think it may help. But should we take this 10% from payer (project)?

**Comment by yegor256** [comment]
@g4s8 yes, I think so. Just like we take now some fee for sending PayPal, we will take a similar fee for sending ZLD, but bigger. Yet another option is to make ZLD-to-BTC conversion cheaper for Zerocracy users. Say, 2% instead of 8%.

**Comment by amihaiemil** [comment]
@yegor256 

> 1. Multiple payment options make Zerocrat software too complicated

Well, PayPal and Zold are just 2, not so many :)

> 2. When something goes wrong, Zerocrat has to hold the money and technically act as a bank

0crat will act as a bank in any scenario.

> 3. PayPal will require "some extra document, bla-bla-bla."

Well, why don't you ask for an official B2B Integration Offer and see what they say? Were you ever thinking a big business like 0crat would fly under the radar? :D

**Comment by yegor256** [comment]
@amihaiemil ever tried to deal with large enterprises?) They don't listen to reason. They just do what they do.

**Comment by krzyk** [comment]
@yegor256 According to https://blog.zold.io/2018/12/09/btc-to-zld.html we can convert only 4 ZLD to BTC per day, is that still true? That means ~ 4$ per day. That makes it ~$124 per month, that's ~ 15 DEV tasks with minimal rate ($16). So one 30min task per 2 days. It is quite limiting.

**Comment by yegor256** [comment]
@krzyk we will remove this limitation to Zerocracy members, of course.

**Comment by denis-konovalyenko** [comment]
> @amihaiemil ever tried to deal with large enterprises?) They don't listen to reason. They just do what they do.

@yegor256 , I was wondering whether you had ever considered [Payoneer](https://www.payoneer.com/) as an alternative in this regard?

**Comment by krzyk** [comment]
@denis-konovalyenko yes he did: https://github.com/zerocracy/farm/issues/865#issuecomment-375666629

**Comment by krzyk** [comment]
@g4s8 Actually if ZLD will work as intermediate gateway (like current debt in 0crat), like Zerocracy -> ZLD -> USD/EUR I'm fine with receiving ZLD. I'm just not quite aware what conversion options exist right now for ZLD, besides BTC.

**Comment by carlosmiranda** [comment]
@g4s8 @yegor256 I concur with all the objections... the current issue is that ZLD is not too reliable; I am fine with an extra fee for paypal if it means there is at least some way I know I can get paid. At least that should give some incentive to people to try to switch to ZLD.

**Comment by emilianodellacasa** [comment]
@g4s8 @yegor256 Please see issue #1901

**Comment by emilianodellacasa** [comment]
@yegor256 I guess this issue cannot be completed until zold-io/wts.zold.io#139 is solved. For reference, I lost $70 while testing if process was working - it doesn't.

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.11`

**Comment by g4s8** [comment]
Done - paypal option was removed

**Comment by 0crat** [comment]
Job [#1860](https://github.com/zerocracy/farm/issues/1860) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1860](https://github.com/zerocracy/farm/issues/1860) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
