### ISSUE TITLE
When wallet is ZLD payments should not go to debts

### ISSUE THREAD

**Issue by emilianodellacasa** [zerocracy/farm#1900]
I set my wallet to ZLD to test the process if/when paypal will be removed.

I saw that all payments Zerocracy makes to me are add to debt list. This does not make sense for a micropayment system as Zold, where there are no transaction fees. 

When the wallet of a user is set to ZLD, Zerocracy should pay immediately to the wallet.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@emilianodellacasa 0crat is adding payments to debts for few reasons, see https://www.zerocracy.com/policy.html
 - paymant was failed (e.g. due to network issues or payment API error)
 - debt already exist
 - payment is too small
we should not add payment to debts if wallet was set to ZLD only in case if payment is too small. Are you sure that you didn't have any debt before patment or wts API worked fine? What is your debt reason (you can check it in telegram message)?

**Comment by emilianodellacasa** [comment]
@g4s8 This is what the bot says:

We are very sorry, but we failed to pay you $7.83 for #294: "The amount $7.83 is too small at: Payment for #294: Payment to ARC for a closed pull request, as in §28"; this amount was added to the list of payments we owe you; we will try to send them all together very soon; we will keep you informed, see §20

I agree that if payment method is Paypal or BTC, we shouldn't pay small amounts because there are transaction fees involved. However, my wallet is ZLD and Zold has been created for microtransactions.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1900](https://github.com/zerocracy/farm/issues/1900), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1900` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa)

**Comment by g4s8** [comment]
@emilianodellacasa it was fixed in https://github.com/zerocracy/farm/commit/21fa186f3ac5ab3ca19b3c0c050e69ead9b0ee46 and released.
Now 0crat will send Zold even if payment is small. Also it will send small debts (< $64).

**Comment by 0crat** [comment]
Job [#1900](https://github.com/zerocracy/farm/issues/1900) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1900](https://github.com/zerocracy/farm/issues/1900) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
