### ISSUE TITLE
Add a way to limit number of REV jobs assigned

### ISSUE THREAD

**Issue by krzyk** [zerocracy/farm#1906]
Similarly to `maxJobsInAgenda` I think it would be beneficial to have an option of `maxRevJobsInAgenda`, so a REV jobs limit could be set by the user. Currently there is no such limit.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1906](https://github.com/zerocracy/farm/issues/1906), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#1906` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by vzurauskas** [comment]
@g4s8 Could this issue receive a boost? The number of PRs in my agenda is getting unmanageable.

**Comment by g4s8** [comment]
@vzurauskas can you try to fix it? I can assign it to you if you want

**Comment by vzurauskas** [comment]
@g4s8 I'll see if I find some time to look into it and will get back at you.

**Comment by vzurauskas** [comment]
@g4s8 Ok, I'll fix it. Can you assign me? Do I need to join the project for this?

**Comment by g4s8** [comment]
@vzurauskas yes, please apply to `C3NDPUA8L` project, for implementation you can check `elect_performer.groovy` script, `VsOptionsMaxJobs` class and search for `maxJobsInAgenda` property.

**Comment by g4s8** [comment]
@0crat assign @vzurauskas

**Comment by 0crat** [comment]
> @0crat assign @vzurauskas  ([here](https://github.com/zerocracy/farm/issues/1906#issuecomment-507224330))

@g4s8 @g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1906](https://github.com/zerocracy/farm/issues/1906), see [§21](http://www.zerocracy.com/policy.html#21); @vzurauskas[/z](https://www.0crat.com/u/vzurauskas) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
@0crat[/z](https://www.0crat.com/u/0crat) I see that you unassigned this issue; the order is still assigned to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by vzurauskas** [comment]
@g4s8 I'm trying to figure out how to check whether a job which is in `Agenda` is DEV or REV. As far as I can tell, `Wbs#role` can be used for that, but in order for that to work, the task has to be in `Wbs`. There are tests, where jobs which are not in `Wbs` are being added to `Agenda`, e.g. in [up6okb_elections_dont_exceed_max_jobs_option](https://github.com/zerocracy/farm/tree/master/src/test/resources/com/zerocracy/bundles/up6okb_elections_dont_exceed_max_jobs_option) bundle. Is it a valid state for a job to exist in `Agenda` but not in `Wbs`? How do I determine job's role in such case?

**Comment by g4s8** [comment]
@vzurauskas please check `elect_performer` script, where some voters can be applied to `DEV` jobs only, e.g. `VsNoRoom` or `VsOptionsMaxJobs`, we need the same but for `REV`

**Comment by vzurauskas** [comment]
@g4s8 `VsOptionsMaxJobs` rule compares the number of all jobs (both DEV and REV) to the limit set in options, and just ignores the result if the new job is REV. If I did the same for `VsOptionsMaxRevJobs` (i.e. count all jobs in agenda, but ignore the result if the new job is DEV), we would have a situation where, say, maxJobs=4 and MaxRevJobs=4, but an agenda with 2 DEV and 2 REV jobs would be "full" because the total is 4. Or a situation where MaxJobs=5, MaxRevJobs=3, there are 2 DEV jobs and 3 REV jobs in the agenda, and no more DEV jobs can be added.

I think it would make more sense if `VsOptionsMaxRevJobs` used the number of total DEV jobs, not the number of all jobs. But then it needs to determine the role of the jobs in `Agenda` somehow.

Or is it actually fine if it just counted all jobs?

**Comment by g4s8** [comment]
@vzurauskas got it, I think you need to create new method in `Agenda`: `String role(String job)`, see `Agenda.add()` method, it saves the role (`DEV` or `REV`) to `agenda.xml`, but then this value is never used. 
I'd not modify  `VsOptionsMaxJobs`, because it has zero multiplier for `REV` jobs.

**Comment by g4s8** [comment]
@rultor release, tag=`0.48.1`

**Comment by g4s8** [comment]
@rultor release, tag=`0.48.1`

**Comment by vzurauskas** [comment]
@g4s8 I just tried setting the new option, and Zerocrat told me "Incorrect option; Possible options are: "maxJobsInAgenda"".

Did we miss something or does it need some time to catch up?

**Comment by g4s8** [comment]
@vzurauskas it seems you didn't update `change_option.groovy` script

**Comment by vzurauskas** [comment]
@g4s8 Ok, new PR: https://github.com/zerocracy/farm/pull/2114

**Comment by g4s8** [comment]
@rultor release, tag=`0.48.2`

**Comment by vzurauskas** [comment]
@krzyk Done. Can this be closed?

**Comment by krzyk** [comment]
@vzurauskas thanks

**Comment by 0crat** [comment]
Job [#1906](https://github.com/zerocracy/farm/issues/1906) is not in the agenda of @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job [#1906](https://github.com/zerocracy/farm/issues/1906) is not in the agenda of @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), can't inspect

**Comment by 0crat** [comment]
The job [#1906](https://github.com/zerocracy/farm/issues/1906) is now out of scope

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/zerocracy/farm/issues/1906#issuecomment-512524483))

@sereshqua The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
