### ISSUE TITLE
Refuse penalty depending on time

### ISSUE THREAD

**Issue by g4s8** [zerocracy/farm#1926]
I think refuse penalty should differ and depends on duration between order was given and refuse time, for example if performer refuse right after assignment it's not critical at all and 0crat may not give a penalty, but if performer refuses after 6 days, it may not be good for a project, I suppose it may lead programmers to refuse as soon as possible if they can't do that job. I'm suggesting this values for refuse:
 - refuse same day as order was given: `0 points`
 - 1 to 3 days: `-10 points`
 - 3 to 6 days: `-20 points`
 - 6 to 10 days: `-50 points`

Also, we can add extra penalty points if refused job has impediment.

**Comment by Protagores** [comment]
@g4s8 The problem with 0 points refuse penalty in the same day is that, it would give performers some luxury of choosing tasks themselves without consequences (to an extent), and by doing so they would become less _manageable_. The whole point of @0crat is that the job assignment process should be fully automatic and bypassed as little as possible, by either side.

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/farm/issues/1926#issuecomment-508722446); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by Protagores** [comment]
@yegor256 What is your opinion?

**Comment by Protagores** [comment]
@g4s8 Also another point to mention here. The more jobs a performer refuses to take, no matter the time, the more possible it is that s/he is a weak performer and teammate, therefore deserving less payment for each job completed overall than other performers who are stronger than him/her.

One of the rep points’ purposes is to measure the ability of each participant to find and implement solutions within the scope of a _project_, not a single stack. In other words, if a project is built around Java, SQL, and XSLT, but you as a programmer only know Java, you should **not** apply for it even if majority of tasks are Java-specific. If you don’t know how SQL or XSLT work, the plan to “accept only Java-specific tasks” just won’t work well for the project, because your ‘solutions’ to those tasks will generally do it more harm than good. And if you do know, then you shouldn’t be afraid to take SQL and XSLT centered tasks anyway, so all is good. I think that’s the idea here.

**Comment by g4s8** [comment]
@Protagores 
> The problem with 0 points refuse penalty in the same day is that, it would give performers some luxury of choosing tasks themselves without consequences

I don't see any issue here, if performer doesn't want to take a job, and resigns it without delay (1 day looks acceptable), the project loses nothing, because this job will be reassigned quickly. So my point is if performer wants to work around of 0crat management, it's pretty fine, unless project is not suffering from it.

**Comment by Protagores** [comment]
@g4s8

> I don't see any issue here, if performer doesn't want to take a job, and resigns it without delay (1 day looks acceptable), the project loses nothing, because this job will be reassigned quickly. So my point is if performer wants to work around of 0crat management, it's pretty fine, unless project is not suffering from it.

This statement might be valid for projects with a small amount of tasks. However, as a project grows, predictability in management becomes more and more important.

One might argue that, if a particular task looks unappealing, you can just add a boost factor to increase the chances that the solution would be delivered in time. But what if there’s a certain percentage of such tasks (I’m talking at least tens and hundreds), and all are more or less equally important? Identifying and boosting each of them will be a) too tedious for its own sake, and b) liable to spoil the performers, making you the project owner too dependent on the boosting mechanism. This is one of the instances where slight but properly applied punishments would be much more effective than simply rewards.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1926](https://github.com/zerocracy/farm/issues/1926), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by yegor256** [comment]
@g4s8 I like this idea

**Comment by g4s8** [comment]
@rultor release, tag=`0.49.19`

**Comment by g4s8** [comment]
Done

**Comment by 0crat** [comment]
Job [#1926](https://github.com/zerocracy/farm/issues/1926) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#1926](https://github.com/zerocracy/farm/issues/1926) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
