### ISSUE TITLE
start Zold beneficiary name with @

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#1978]
When you call `/do-pay` in WTS, you should start the name of the beneficiary with `@` sign, to avoid confusions. Please, implement it ASAP.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#1978](https://github.com/zerocracy/farm/issues/1978), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@rultor release, tag=`0.45.21`

**Comment by yegor256** [comment]
@g4s8 I believe it's fixed

**Comment by 0crat** [comment]
I'm not managing `zerocracy/farm` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
The job [#1978](https://github.com/zerocracy/farm/issues/1978) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
