### ISSUE TITLE
new metric: total amount of projects

### ISSUE THREAD

**Issue by yegor256** [zerocracy/farm#2035]
Let's add a new metric: the total amount of projects we manage now. Let's collect it the way we collect other metrics and include it the regular report to the PMO.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) not enough funds available in the project, can't set budget of job [#2035](https://github.com/zerocracy/farm/issues/2035), see [§21](http://www.zerocracy.com/policy.html#21); @g4s8[/z](https://www.0crat.com/u/g4s8) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#2035` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@yegor256 it was fixed in #2037 PR, can we close?

**Comment by 0crat** [comment]
Job [#2035](https://github.com/zerocracy/farm/issues/2035) is not in the agenda of @g4s8[/z](https://www.0crat.com/u/g4s8), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#2035](https://github.com/zerocracy/farm/issues/2035) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)
