### ISSUE TITLE
Architecture around Question.java

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#503]
As far as I can tell, all the chatting logic is inside the [radars](https://github.com/zerocracy/farm/blob/master/src/main/java/com/zerocracy/radars) package and the central object is [Question.java](https://github.com/zerocracy/farm/blob/master/src/main/java/com/zerocracy/radars/Question.java). 

There are a number of issues with class Question:

1) It does not have an interface, so currently we are bound 100% to the XML/regex implementation (and 0crat advertises as AI!). It should definetely be an interface and have implementations ``RegexQuestion`` and ``AiQuestion``.

2) The understanding logic should not be inside Question, it should be inside an implementation of Language -- why not make the bot speak more languages? If we had a Language, then there would be a single implementation of Question, which would just animate the comment received from Github/Telegram/Slack. And there would be XmlLanguage (decorated with English, French etc) and AiLanguage (decorated the same).

And in general, I noticed that the XML/regex stuff is spread accross the project -- is this OK? I understand it is a first version and we can't implement AI for various reasons yet, but at least we should have the architecture in code for it: interfaces, abstraction, so we can easily switch when we'll have an AI service available.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil our previous software had way more of that "AI" inside the interface. However, our 2-years experience demonstrated that the AI in the interface only makes it less convenient. It's way easier to communicate with a bot that perfectly understands 10 commands in a very specific, simple and explicit syntax like "assign me", instead of talking to Siri-style pseudo-AI boots which are designed to understand "can you please assign me", but make a lot of mistakes.

We, programmers, are not so stupid. We can remember 10 commands and use them. No need to design AI in the bot.

The AI will be added to the other part of the product -- to the management side. We need AI in order to make management decisions, like: "who is the next programmer to fire" or "how many more bugs are required in order to increase the quality of the next release". This is where we need AI. Bots should be simple.

Make sense?

**Comment by amihaiemil** [comment]
@yegor256 I see... ok then, closing this :)

**Comment by 0crat** [comment]
Job `gh:zerocracy/farm#503` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#503](https://github.com/zerocracy/farm/issues/503) was not in scope
