### ISSUE TITLE
Elections and Agenda should work together

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#788]
Currently, the elections and the agenda stakeholders (as well as java classes) are completely separate modules. The flow works fine just because they happen to be run sequencially, in the right order. 

However, these 2 concepts should work together, in the same unit: once a performer is elected (is assigned a job, an order), then they should automatically have the agenda updated. Now, if the order of the stakeholders' execution gets broken somehow, who knows what weird bugs we could get since all the logic is turned upside down.

I assume the problem is in other places as well, I've noticed that the whole system is very fine grained into separate modules, stakeholders, and order matters a lot.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil elections should not affect the agenda, since they are not orders yet. You may be elected for a job but will never get it, because, for example, ARC will assign someone else there manually. The only place where the order is actually placed in `start_order.groovy`. It issues a claim of type `Order was given`. This claim will be picked up by `add_to_agenda.groovy` and the agenda will be updated. It's bullet proof :)

The idea of the entire design is to have individual stakeholders absolutely independent on each other. They do their jobs and don't care about others.

**Comment by amihaiemil** [comment]
@yegor256 you mean individual procedures :(

**Comment by yegor256** [comment]
@amihaiemil yes, exactly them :)
