### ISSUE TITLE
Model form zerocracy/datum should be put in this repo

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#795]
See [this](https://github.com/zerocracy/farm/pull/784#pullrequestreview-102938652) discussion. Some changes in the codebase required changes in the ``.xsd`` from the model. This created a nasty dependency between the 2 repos and their releases. 

I think the model should be put in this repo, to get rid of this dependency. WDYT?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil we will still need to release twice, I think. Since `Xocument` depends on a specific version of the XML model. During testing/building/releasing this version of the model won't be available and we won't be able to release. Thus, we will have to release XML first, anyway.

**Comment by amihaiemil** [comment]
@yegor256 I don't understand, isn't ``Xocument`` in ``jcabi-xml``, which is supposed to be a generic library? Why is that a dependency?

**Comment by yegor256** [comment]
@amihaiemil `Xocument` is in this repo, see `com.zerocracy.Xocument`

**Comment by amihaiemil** [comment]
@yegor256 So what is the issue about that version? It could always be the project's current version, no? 

And maybe, the issue now is also that paths to ``.xsd`` files are absolute, ``datum.zerocracy.com/...`` -- they could also be relative, right?

**Comment by yegor256** [comment]
@amihaiemil well, I wanted to keep these two repositories separate for the sake of stability. The XML model lives its own live and is rather stable. The Farm is much more dynamic and changes multiple times a day. The policy is yet another artifact that also has its own lifecycle. I'm going to introduce yet another artifact in the future, which will be responsible for the AI/ML part of the whole show. It will analyze the XML artifacts and make smart decisions about your project: what needs to be done in order to make it better, find risks/threats, suggest new people/tasks/etc.

**Comment by amihaiemil** [comment]
@yegor256 maybe ``/datum`` holds more stuff than I am aware of, but I am referring strictly to the ``.xsd`` files which validating XMLs and will complain if some class in ``/farm`` changes attributes -- only those classes, could they be moved to ``/farm``?

**Comment by yegor256** [comment]
@amihaiemil let's keep it the way it is for now. I do understand the confusion, but let's see how both repositories will progress and make the decision later.

**Comment by amihaiemil** [comment]
@yegor256 ok; I close this for now, then
