### ISSUE TITLE
Tasks slots should be per project, not per platform

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/farm#804]
Currently, the number of allowed tasks covers all the projects. This is too little, 8 (or even 12) task slots in, let's say, 3 projects are not enough. 

Task complexity and delivery speed are depending a lot on the project and how fast the team as a whole moves in that project. Besides, if the number of possible tasks is global, then one project could "starve", the DEVs could be assigned to other projects all the time.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil I agree that we should try to balance tasks between projects: https://github.com/zerocracy/farm/issues/808

**Comment by yegor256** [comment]
@amihaiemil I've seen this problem before, that's why decided to put those limits. When a developer has too many tasks in the agenda, he/she can't really perform well and _all_ projects suffer. I believe, we must keep the limits rather strict.

The developer is always interested to clear the agenda, in order to get new takss.

**Comment by amihaiemil** [comment]
@yegor256 I see. And what would that new class do exactly? "take into account only orders currently assigned to each person in this particular project" is not so precise :D

**Comment by yegor256** [comment]
@amihaiemil it's better to ask in #808

**Comment by amihaiemil** [comment]
@yegor256 I close this, then, and discuss there :D
